name: Node CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - name: Runs NodeJS CI Action
      uses: pondevelopment/actions/nodejs@main
      with:
        NPM_REGISTRY_TOKEN: ${{secrets.NPM_TOKEN}}
        NODE_VERSION: ${{ matrix.node-version }}
  
  sonar:
    runs-on: ubuntu-latest
    needs: [test]
    steps:    
    - name: Runs SonarCloud Action
      uses: pondevelopment/actions/sonarcloud@main
      with:
        NPM_REGISTRY_TOKEN: ${{ secrets.NPM_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}